config/routes.rb
SampleApp::Application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@title = "Home"
  end

  def help
    #@title = "Help"
  end

  def about
    #@title = "About"
  end

  def contact
    #@title = "Contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Sample App | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Sample App</h1>
<h2>About page</h2>
<%= link_to "Home",  static_pages_home_path %>
<%= link_to "Help",  static_pages_help_path %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Sample App</h1>
<h2>Contact page</h2>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Sample App</h1>
<h2>Help page</h2>
<%= link_to "Home", :controller => "static_pages", :action => "home" %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<h1>Sample App</h1>
<h2>Home page</h2>
<p>This is home page for my Rails tutorial</p>